# Generated by Django 4.2.16 on 2024-10-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_historialpaciente_fecha_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotratamiento',
            name='categoria',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
