# Generated by Django 4.2.16 on 2024-10-27 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tipotratamiento_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='facturatratamiento',
            name='tratamientos',
            field=models.ManyToManyField(related_name='facturas', to='core.tratamiento'),
        ),
        migrations.AlterField(
            model_name='tipotratamiento',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='tipo_tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipotratamiento'),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='core.especialidad')),
            ],
            options={
                'unique_together': {('especialidad', 'nombre')},
            },
        ),
        migrations.AlterField(
            model_name='tipotratamiento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_tratamientos', to='core.categoria'),
        ),
        migrations.AlterUniqueTogether(
            name='tipotratamiento',
            unique_together={('categoria', 'nombre')},
        ),
        migrations.RemoveField(
            model_name='tipotratamiento',
            name='especialidad',
        ),
    ]
