# Generated by Django 4.2.16 on 2024-10-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_empleado_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
